# Generated by Django 6.0.5 on 2026-05-30 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player_registration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='aadhaar_number',
        ),
        migrations.RemoveField(
            model_name='player',
            name='current_team',
        ),
        migrations.RemoveField(
            model_name='player',
            name='id_proof',
        ),
        migrations.RemoveField(
            model_name='player',
            name='jersey_size',
        ),
        migrations.RemoveField(
            model_name='player',
            name='previous_experience',
        ),
    ]
